### ISSUE TITLE
Error: Cannot find module './objects'

### ISSUE THREAD

**Issue by Thijs-Velde** [not-an-aardvark/snoowrap#1]
On a fresh install of 0.9.2, the following error occurs.
The objects folder is missing after install. Is this a problem with my node install or with snoowrap?

```
module.js:341
    throw err;
    ^

Error: Cannot find module './objects'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (B:\Users\thijs\Dropbox\Code\wallpaper-fetcher\node_modules\snoowrap\lib\snoowrap.js:843:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (B:\Users\thijs\Dropbox\Code\wallpaper-fetcher\app.js:4:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

**Comment by not-an-aardvark** [comment]
Whoops, that's a bug -- it looks like I'd configured it so that NPM would ignore subfolders.

I'm pushing 0.9.3 in a few minutes -- that should hopefully fix things.
