### ISSUE TITLE
RequestError: Error: getaddrinfo EAI_AGAIN oauth.reddit.com:443

### ISSUE THREAD

**Issue by diegokfu** [not-an-aardvark/snoowrap#101]
Sometimes it random crash with the following error:
`
Unhandled rejection RequestError: Error: getaddrinfo EAI_AGAIN oauth.reddit.com:443
    at new RequestError (/home/card/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/home/card/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/home/card/node_modules/request/request.js:188:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/home/card/node_modules/request/request.js:884:8)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
`

And i'm using try catch in every function, so probably there is no problems in my side

**Comment by not-an-aardvark** [comment]
Thanks for the report. This means that a DNS lookup failed for the `oauth.reddit.com` domain, which might be related to your network connectivity. It's not something that can be fixed in snoowrap.
