### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'map' of null - Bug?

### ISSUE THREAD

**Issue by JimmyPrice** [not-an-aardvark/snoowrap#130]
Hey

My code runs correctly but I continuously get this error message, about every 30 seconds:

Unhandled rejection TypeError: Cannot read property 'map' of null
at EventEmitter.comments.on (/Users/user/dev/bot/bot.js:36:43)
at emitOne (events.js:96:13)
at EventEmitter.emit (events.js:188:7)
at /Users/user/dev/bot/node_modules/snoostorm/main.js:59:19
at Listing.forEach (native)
at /Users/user/dev/bot/node_modules/snoostorm/main.js:58:55
at tryCatcher (/Users/user/dev/bot/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/user/dev/bot/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/Users/user/dev/bot/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/Users/user/dev/bot/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/Users/user/dev/bot/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/Users/user/dev/bot/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/Users/user/dev/bot/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/Users/user/dev/bot/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

Any feedback would be greatly appreciated

Many thanks

**Comment by not-an-aardvark** [comment]
This looks like a bug in your code. Try looking on line 36 of your `bot.js` file to make sure you're not calling a `.map` method on a null value.

**Comment by JimmyPrice** [comment]
Sorry, this was just a silly mistake on my part. Fixed now.
