### ISSUE TITLE
Unhandled rejection TypeError: Promise chain rejection: Cannot read property 'indexOf' of undefined.

### ISSUE THREAD

**Issue by 45Green** [not-an-aardvark/snoowrap#144]
`Unhandled rejection TypeError: Promise chain rejection: Cannot read property 'indexOf' of undefined.
    at E:\node_modules\promise-chains\index.js:58:15
    at tryCatcher (E:\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
`
My friend reported me about that problem, it doesn't break script, but annoying.

**Comment by not-an-aardvark** [comment]
Closing because not enough information was provided to figure out what's going on.
