### ISSUE TITLE
Searching for subreddit that does not exist, causes a crash (exit code: 1)

### ISSUE THREAD

**Issue by chrisphilipov** [not-an-aardvark/snoowrap#148]
Attempting to search for a subreddit name using the "searchSubredditNames" function causes a crash if the "exact" flag is set to true and the query is a string for a subreddit which does not exist. Function call to reproduce: 
```javascript
r.searchSubredditNames({query: 'jkhjkhh', exact: true}).then(console.log);
```
Expected behaviour based on documentation should be an empty array, but it crashes everything. Setting the exact flag to false and running the same query produces an empty array as expected. Testing was done on latest version from npm: 1.15.2

**Comment by not-an-aardvark** [comment]
Thanks for the report. Could you provide more details about the crash? Does a stack trace get printed?

**Comment by chrisphilipov** [comment]
Hello, unfortunately I could not give you further detail. No stack trace gets printed. Try/catch methods do not catch anything, cause of the asynchronous nature of the calls. It just seems to fail after trying to fulfil the promise.

**Comment by SpyTec** [comment]
Ran this myself just now. We do get an error returned from Reddit with this. Since you are using `exact` as a parameter you have to find a subreddit - otherwise 404 will be returned.

For me this is correct behaviour, so I'm closing the issue

```
StatusCodeError: 404 - {"message":"Not Found","error":404}
    at new StatusCodeError (node_modules/request-promise-core/lib/errors.js:32:15)
    at node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

You can handle it quite easily though
```js
try {
  const results = await r.searchSubredditNames({query: 'jkhjkhh', exact: true});
}
catch (error) {
  if (error instanceof StatusCodeError) {
    console.log("handling error");
  }
}
```
