### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by TheAppleFreak** [not-an-aardvark/snoowrap#151]
I'm using Snoowrap in a distributed application to act as a Reddit interface service, and in general it's been working fantastically for me. However, recently I did some reorganization of each service, and I began getting some strange TimeoutOverflowWarnings. To my knowledge, this doesn't impact how Snoowrap itself functions; everything appears to work just fine. If I had to take a wild stab at the cause of 

First, here's the code repo. I don't think I'm doing anything out of the ordinary here: https://gitlab.com/pcmasterrace/pcmrbot.js/core/reddit

Here's the output from a 16 hour run of the service (once it spits out `Infinity` a few times it stops):

```
(node:11424) TimeoutOverflowWarning: 15312007288176780 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 153135384889056130000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 1.5313538642025685e+24 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 15312007266936056 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 15312007644400772 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 15312008044462088 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 153135384677855900000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 153135388452855840000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 153135392453955800000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 1.5313538620905686e+24 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 1.5313538998405686e+24 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: 1.5313539398515686e+24 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:11424) TimeoutOverflowWarning: Infinity does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

And here's one instance of it with `--trace-warnings` enabled:

```
(node:8332) TimeoutOverflowWarning: 153141300125296720000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
    at new Timeout (internal/timers.js:57:15)
    at setTimeout (timers.js:403:19)
    at Function.Promise.delay (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\timers.js:26:18)
    at snoowrap._awaitRequestDelay (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\snoowrap\dist\request_handler.js:165:28)
    at C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\snoowrap\dist\request_handler.js:83:18
    at tryCatcher (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\name\Documents\Node\pcmrbot.js\core\reddit\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

On those reorganizations I touched on earlier, the biggest change was that each individual service was made into its own Node app and repository (previously, each service was in its own folder in a single repository with a single `node_modules` for all services). I don't personally understand why just moving it into its own repo would cause these messages, but ¯\_(ツ)_/¯

As I said, the logging doesn't appear to impact the functionality of the service, so I don't think it's super high priority. Figured it'd be worth reporting regardless, though.

**Comment by TheAppleFreak** [comment]
So it's been about 10 months since I made this issue, and I haven't seen this problem recur. Gonna close this for now; I'll reopen it or make a new issue for it if I see this happen again.
