### ISSUE TITLE
read_all_messages leads to Error 429

### ISSUE THREAD

**Issue by please-wait** [not-an-aardvark/snoowrap#26]
Before, I had this problem when there were no unread messages, but now everytime I try `snoowrap.read_all_messages()` I get:

    Unhandled rejection StatusCodeError: 429 - [object Object]
        at new StatusCodeError (C:\a\node_modules\snoowrap\node_modules\request-promise\lib\errors.js:26:15)
        at Request.RP$callback [as _callback] (C:\a\node_modules\snoowrap\node_modules\request-promise\lib\rp.js:68:32)
        at Request.self.callback (C:\a\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:199:22)
        at emitTwo (events.js:100:13)
        at Request.emit (events.js:185:7)
        at Request.<anonymous> (C:\a\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:1036:10)
        at emitOne (events.js:95:20)
        at Request.emit (events.js:182:7)
        at IncomingMessage.<anonymous> (C:\a\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:963:12)
        at emitNone (events.js:85:20)
        at IncomingMessage.emit (events.js:179:7)
        at endReadableNT (_stream_readable.js:913:12)
        at _combinedTickCallback (node.js:377:13)
        at process._tickCallback (node.js:401:11)

As far as I know this is because the server is receiving too many requests but I have increased the `request_delay` of the config file and it still gives me the error.

**Comment by not-an-aardvark** [comment]
I think this is actually be an issue/feature with the reddit API, not with snoowrap itself. It seems like the reddit API has started harshly ratelimiting requests (i.e. only allowing one request every few minutes) to the `/api/read_all_messages` endpoint since about a month ago. ([Here's](https://www.reddit.com/r/redditdev/comments/4dozgt/failed_to_load_resource_the_server_responded_with/) a post on /r/redditdev talking about it.)

If you want to use the snoowrap function and ignore all 429 errors, you can do something like this:

```js
r.read_all_messages().catch({statusCode: 429}, function() {})
```

...which essentially ignores all 429 errors with a no-op function, while still rejecting the Promise if any other errors appear.

**Comment by please-wait** [comment]
Thanks for the answer. I was probably just testing too harshly!

For future reference, I think it would be a good idea to have a "try again" function inside the catch since the messages are still unread. However, if retrying is in a few seconds after the first error, it will definitely lead to the same error.
