### ISSUE TITLE
Attempted to call undefined which is not a function (v1.5.0, from NPM)

### ISSUE THREAD

**Issue by MayorMonty** [not-an-aardvark/snoowrap#37]
By, the way, here's some information to help with debugging:
Snoowrap v1.5.0 installed via npm
node v6.2.2

<hr />
I'm trying out snoowrap, using it for a replication script I'm making. So, I got the subreddit name:
```javascript
reddit.get_subreddit("vexforum")
```
Working well, but I notice that it does not return a `Promise`, it is a blocking function that returns a `Subreddit` class: 
```javascript
> reddit.get_subreddit("vexforum")
Subreddit { display_name: 'vexforum' }
```

This is odd, but I ignore it for now. I then try to call `.create_selfpost()`, and I reach the crux of my problem:
```javascript
reddit.get_subreddit("vexforum")
  .create_selfpost({
    "title": "Testing 1...2...3...",
    "text": "Don't Mind Me!"
  })
```

Will give the following error:
```
Unhandled rejection TypeError: Promise chain rejection: Attempted to call undefined which is not a function.
    at /Users/tim/Documents/Projects/node_modules/promise-chains/index.js:68:15
    at tryCatcher (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/async.js:148:10)

    at Immediate.Async.drainQueues [as _onImmediate] (/Users/tim/Documents/Projects/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
```

Let's break down what we know:
```
Unhandled rejection TypeError:
```
This means I haven't handled my errors in my promises right, and it irrelevant.
```
Promise chain rejection:
```
Something in the Promise chain has called `reject()`, most likely the `.create_selfpost()` function.
```
Attempted to call undefined which is not a function
```
Something tried to call an undefined variable as if it were a function.

Any help would be awesome! Thanks!

**Comment by not-an-aardvark** [comment]
Hello, thanks for the bug report.

> ```js
reddit.get_subreddit("vexforum")
```

> Working well, but I notice that it does not return a Promise, it is a blocking function that returns a Subreddit class

To clarify, this did not return a Promise because snoowrap uses lazy getters. In other words, a new `Subreddit` object was created, but nothing has actually been fetched from the reddit server yet, so it's not really "blocking" since it's not waiting for any request to complete.

> This is odd, but I ignore it for now. I then try to call .create_selfpost(), and I reach the crux of my problem:

> ...
> `Unhandled rejection TypeError: Promise chain rejection: Attempted to call undefined which is not a function.`

I'm guessing that issue occurs because the function is supposed to be [`submit_selfpost()`](https://not-an-aardvark.github.io/snoowrap/Subreddit.html#submit_selfpost__anchor), not `create_selfpost`. Although now that I look at the readme, it seems like the example uses `create_selfpost`; I'll fix that.

**Comment by not-an-aardvark** [comment]
I closed this issue since I think the misleading code in the readme was the only problem, but feel free to reopen it if it's still not working after switching to `submit_selfpost()`.

**Comment by MayorMonty** [comment]
Sorry about that, I knew it was probably my fault, but I wanted to raise it to your attention anyways. Very useful framework, though!
