### ISSUE TITLE
Recieving Invalid grant Error even though all credentials are correct.

### ISSUE THREAD

**Issue by grogugrogu** [not-an-aardvark/snoowrap#379]
Unable to post on to reddit despite having all correct credentials.
```
exports.redditPost = async (subreddit) => {
  const redditBot = new snoowrap({
          userAgent: `${process.env.REDDIT_USER_AGENT}`, 
          clientId: `${process.env.REDDIT_CLIENT_ID}`,
          clientSecret: `${process.env.REDDIT_CLIENT_SECRET}`,
          username: `${process.env.REDDIT_USERNAME}`,
          password: `${process.env.REDDIT_PASSWORD}`
      });
  try{
  await redditBot.getSubreddit(subreddit).submitLink({
              title: 'Title of Post',
              url: `https://example.com`,
          })
  } catch(err){
  console.log(err)
  }
}
```
Error: "Invalid grant" error returned from reddit. (You might have incorrect credentials.)
    at /Users/name/GitHub/project/Main/node_modules/snoowrap/dist/request_handler.js:280:15
    at process.processImmediate (node:internal/timers:471:21)
From previous event:
    at snoowrap.updateAccessToken (/Users/name/GitHub/project/Main/node_modules/snoowrap/dist/request_handler.js:275:8)
    at /Users/name/GitHub/project/Main/node_modules/snoowrap/dist/request_handler.js:83:18
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

**Comment by grogugrogu** [comment]
Solved this issue. Don't use special characters in your reddit password or characters in sequence like 123 or abc. Seems like since the reddit api is based off of older reddit, the relics are still intact.
