### ISSUE TITLE
` Unhandled rejection ReferenceError:  is not defined` probably related to `_fulfillmentHandler0`

### ISSUE THREAD

**Issue by please-wait** [not-an-aardvark/snoowrap#4]
I try to use snoowrap in Node console (with `--harmony`). I give my client_id, clinet_secret, user_agent and refresh_token. But any action I try to perfrom (like `r.get_hot()` or `r.get_subreddit("gifs")`) I receive:

``` javascript
Promise {
  _bitField: 17825792,
  _fulfillmentHandler0: [ReferenceError:  is not defined],
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
>Unhandled rejection ReferenceError:  is not defined
   at Object.<anonymous> (C:\Sites\mine\node_modules\snoowrap\lib\request_handler.js:42:28)
   at next (native)
   at step (C:\Sites\mine\node_modules\snoowrap\lib\request_handler.js:3:191)
   at C:\Sites\mine\node_modules\snoowrap\lib\request_handler.js:3:451
   at Promise._execute (C:\Sites\mine\node_modules\snoowrap\node_modules\bluebird\js\release\debuggability.js:272:9)
   at Promise._resolveFromExecutor (C:\Sites\mine\node_modules\snoowrap\node_modules\bluebird\js\release\promise.js:474:18)
   at new Promise (C:\Sites\mine\node_modules\snoowrap\node_modules\bluebird\js\release\promise.js:77:14)
   at Object.<anonymous> (C:\Sites\mine\node_modules\snoowrap\lib\request_handler.js:3:99)
   at Object.oauth_request (C:\Sites\mine\node_modules\snoowrap\lib\request_handler.js:68:16)
   at snoowrap.(anonymous function) [as _get] (C:\Sites\mine\node_modules\snoowrap\lib\snoowrap.js:839:41)
   at snoowrap._get_sorted_frontpage (C:\Sites\mine\node_modules\snoowrap\lib\snoowrap.js:338:17)
   at snoowrap.get_hot (C:\Sites\mine\node_modules\snoowrap\lib\snoowrap.js:348:17)
   at repl:1:4
   at REPLServer.defaultEval (repl.js:252:27)
   at bound (domain.js:287:14)
   at REPLServer.runBound [as eval] (domain.js:300:12)
   at REPLServer.<anonymous> (repl.js:417:12)
   at emitOne (events.js:82:20)
   at REPLServer.emit (events.js:169:7)
   at REPLServer.Interface._onLine (readline.js:211:10)
   at REPLServer.Interface._line (readline.js:550:8)
   at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

**Comment by not-an-aardvark** [comment]
Hmm, I can't seem to reproduce this. Could you paste the code you're using? (Obviously, feel free to omit confidential information such as access tokens.)

**Comment by please-wait** [comment]
Thank you for quick response.
I am using it on a windows 10 machine with node v4.4.0

After installing, I start by `node --harmony` in my console
then:

```Javascript
>>var snoo = require("snoowrap");
>> var me = new snoo({
... user_agent: "Blah v0.8.2 by blah",
... client_id: "...",
... client_secret: "...",
... refresh_token: "..." })
```

when I inspect `me`:
```Javascript
> me
snoowrap { user_agent: "Blah v0.8.2 by blah",
  client_id: '...',
  client_secret: '(redacted)',
  refresh_token: '(redacted)',
  access_token: undefined }
```

but any method leads to the error

I get client's id and secret from api page, the refresh_token is gotten from the awesome `reddit-oauth-helper` and the user_agent is just some string I write about my app.  Is there anything I am doing wrong?

**Comment by not-an-aardvark** [comment]
The issue seems to be that the spread operator, which I've been using in the code, works on node 5 but doesn't work on node 4. I just added a babel plugin to transpile the spread operator, so now it should hopefully work on both versions.

Try upgrading to snoowrap@0.9.4 and let me know if that fixes things.

**Comment by please-wait** [comment]
Working perfectly! :+1:
