### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by benwaffle** [not-an-aardvark/snoowrap#53]
occasionally happens when running my code (https://github.com/benwaffle/best-comments)
You can run it by filling out config.js and running main.js

```
Unhandled rejection Error: 150972
    at snoowrap._awaitRatelimit (/home/ben/dev/best-comments/node_modules/snoowrap/dist/request_handler.js:144:11)
    at /home/ben/dev/best-comments/node_modules/snoowrap/dist/request_handler.js:80:18
    at tryCatcher (/home/ben/dev/best-comments/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ben/dev/best-comments/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ben/dev/best-comments/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/ben/dev/best-comments/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/ben/dev/best-comments/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/ben/dev/best-comments/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/ben/dev/best-comments/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

**Comment by not-an-aardvark** [comment]
Thanks for the report; that seems to be coming from [here](https://github.com/not-an-aardvark/snoowrap/blob/371dfe3c52d816699e4a6bbbf063e9dfa66af964/src/request_handler.js#L112). It looks like your script exceeded reddit's ratelimit, so throwing an error was expected behavior. But I think that error is broken; it's supposed to have a descriptive error message.

**Comment by not-an-aardvark** [comment]
For what it's worth, if you want to avoid hitting reddit's ratelimit, you might want to set a request delay:

```js
r.config({requestDelay: 1000}); // send at most one request per second
```

Or alternatively, tell snoowrap to queue requests to fulfill the ratelimit rather than throwing an error:

```js
r.config({continueAfterRatelimitError: true})
```
