### ISSUE TITLE
submission.mark_as_read() returns 403

### ISSUE THREAD

**Issue by please-wait** [not-an-aardvark/snoowrap#6]
My input:

```Javascript
r.get_new( "my sub" ).then( function (posts) {
  posts.forEach(function (post) {
    post.mark_as_read();
  });
});
```

Answer:
```
Unhandled rejection StatusCodeError: 403 - [object Object]
    at new StatusCodeError (C:\Sites\mine\node_modules\snoowrap\node_modules\request-promise\lib\errors.js:26:15)
    at Request.RP$callback [as _callback] (C:\Sites\mine\node_modules\snoowrap\node_modules\request-promise\lib\rp.js:68:32)
    at Request.self.callback (C:\Sites\mine\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (C:\Sites\mine\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (C:\Sites\mine\node_modules\snoowrap\node_modules\request-promise\node_modules\request\request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

**Comment by not-an-aardvark** [comment]
I think that API endpoint is only accessible to accounts that have a reddit gold subscription -- could that be the issue?

(I should probably have noted that in the documentation.)

**Comment by please-wait** [comment]
Yes, your are right.
It makes sense now because a feature of gold accounts is that they can see the visited links across multiple devices.

I just wanted to make sure my bot is not reading a submission twice. So, I think the best approach for me is to make a `var last_post_seen = "post_id"` and fetch the new submissions until I get to that post, right?

**Comment by not-an-aardvark** [comment]
You could probably keep track of it in a cache, e.g.

```js
var posts_seen = {};
r.get_new( "my sub" ).then( function (posts) {
  posts.forEach(function (post) {
    if (!posts_seen[post.id]) {
      // Do stuff with unseen posts here
    }
    // Store this post in the cache so that it doesn't get read twice
    posts_seen[post.id] = true;
  });
});
```

**Comment by please-wait** [comment]
For a few posts maybe what you say is more reliable.

Anyway, I have been experimenting with your code, and it works beautifully! We absolutely needed a library like this. Keep up the good work!

:+1:

**Comment by not-an-aardvark** [comment]
Thanks! I'm glad this is useful.

Since I only recently finished this, I don't really have a good idea of what is intuitive to other people regarding the documentation, the package itself, etc. Feel free to provide feedback if something seems inconsistent/unintuitive. As you've probably figured out, the package is a bit unpolished in a few places.

**Comment by please-wait** [comment]
I would say everything is there. It just needs a bit of digging in the
documentation and trying. I think more code examples can be very very
useful. Also, if you open the wiki of the repo, maybe me and others help
you with the documentation.

**Comment by not-an-aardvark** [comment]
Thanks for the suggestions -- I've actually been meaning to do code examples for awhile. I started adding  them [here](https://not-an-aardvark.github.io/snoowrap/snoowrap.html), but there are still a bunch more to go. Feel free to help out with adding them, if you'd like.

(The documentation is generated automatically from inline comments like [these](/not-an-aardvark/snoowrap/blob/a2fbf53bcd952b0873e52dfe98e62657165c0319/src/snoowrap.js#L99). After cloning the repository and doing `npm install`, you can build the documentaion to a `doc/` folder using running `npm run docs`.)
