### ISSUE TITLE
Getting "SyntaxError: Unexpected token ..."

### ISSUE THREAD

**Issue by ryan4888** [not-an-aardvark/snoowrap#7]
Getting the following error from snoowrap.

```
/server/node_modules/snoowrap/node_modules/promise-chains/index.js:55
    construct: (target, args) => (wrap(target().then(result => (wrap(new result(...args))))))
                                                                                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/server/node_modules/snoowrap/lib/snoowrap.js:7:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/server/controllers/AuthController.js:10:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at module.exports (/server/routes.js:14:14)
```

**Comment by not-an-aardvark** [comment]
Oh right, the promise-chains module uses the spread operator, which only works in node 5. I'll push a fix to that module so that it'll work with node 4 as well.

**Comment by ryan4888** [comment]
@not-an-aardvark awesome. Thanks for the quick reply.

**Comment by not-an-aardvark** [comment]
Alright, I've just pushed promise-chains@0.3.2 which fixes this issue. I believe you should be able to upgrade to that by using `npm upgrade promise-chains`.

**Comment by Pratap-chauhan** [comment]
iam facing a problem..
when i used ng -v command
usr/local/lib/node_modules/@angular/cli/models/config/config.js:17
    constructor(_configPath, schema, configJson, fallbacks = []) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/models/config.js:3:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

anybody can help me

**Comment by not-an-aardvark** [comment]
Hi,

It looks like your syntax is invalid because you're using a default parameter for `fallbacks`.

This doesn't seem to be an issue with snoowrap, and this is not the best place to get help with JavaScript in general. I would recommend asking a question on StackOverflow if you're having trouble with syntax errors in your code.

**Comment by demarcop** [comment]
It might look that way, but it's happening to me too and I have no code of my own yet.  This is not a user JavaScript problem, but something to do with "ng -v"  "ng new blahblah"

All result in the same result.

**Comment by 80017** [comment]
node index.js
/home/software/index.js:3
r.connect(( host: 'localhost',port: 8080 ), function(err, conn) {
                ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by tateviktome** [comment]
Running on the same problem as @chengjaun ... Is there any solution?
