### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Tvde1** [not-an-aardvark/snoowrap#72]
This is the function I use to reply to a comment:
```js
function postComment(id, text) {
	console.log('Replying \''+text+'\' to comment \''+id+'\'.');
	r.getComment(id).reply(text);
}
```
But whenever I execute it, I get this error:
```
Replying 'wow it workie' to comment 'degcsdg'.
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at D:\Bestanden\Reddit\Test bot\node_modules\snoowrap\dist\request_handler.js:232:37
    at tryCatcher (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Bestanden\Reddit\Test bot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```
Any idea to what I am doing wrong?
I have this somewhere above the code:
```js
const r = new snoowrap({
  userAgent: 'Reddit Test Bot by /u/Tvde1',
  clientId: 'id',
  clientSecret: 'secret',
  username: user,
  password: pass
});
```
Of course with the correct data.

**Comment by not-an-aardvark** [comment]
Hmm, that's odd. Does the comment get posted successfully?

**Comment by Tvde1** [comment]
Nope

**Comment by Tvde1** [comment]
Any debugging I can do to help?

**Comment by not-an-aardvark** [comment]
I just tested it out. Under normal circumstances I can't reproduce this issue, but it seems like the issue does occur when the provided password is incorrect. Could that be the problem in your case?

**Comment by Tvde1** [comment]
hmmm I'll investigate

**Comment by Tvde1** [comment]
Silly me, I used the script application on my other account. Thanks for making me check the credentials! Best of luck with this package!

**Comment by not-an-aardvark** [comment]
No worries!

I'm going to reopen this issue though, because this is a misleading error message and could probably be improved.
