### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by olegberman** [not-an-aardvark/snoowrap#93]
Hello, thank you for your work. 

**Reproduce:**
1. Create an app of type "web app" here
2. Try to authenticate with schema ```clientId, clientSecret, username, password```
3. Throws an error 
```Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at /Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/dist/request_handler.js:236:37
    at tryCatcher (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/berman/Documents/projects/meme_trader/node_modules/snoowrap/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Why:**
I went into `/dist/request_handler.js:236:37` and console logged the `tokenInfo` argument from the promise callback and here what it is: ```{ error_description: 'Only script apps may use password auth',
  error: 'unauthorized_client' }```

**Possible solution:**
Check for any occurrence of error property on response objects and print the error to the console.

**Solution on my side:** 
Create an app with type *personal use script*.

**Comment by not-an-aardvark** [comment]
Thanks for reporting, this looks like a bug. Reddit seems to return a 200 response even when something goes wrong in the request, and instead it adds an `error` property to the response like [this](https://github.com/not-an-aardvark/snoowrap/blob/40cba7926c06088da92a1a1667058ef27ff84b29/src/request_handler.js#L209). It would probably be a good idea to check for all `error` keys rather than matching against specific values.

For what it's worth, it's expected that an error should be thrown here, since you can't use password authentication with a web app. But snoowrap should make the error clearer rather than throwing internally.

**Comment by bkoprivi** [comment]
the issue still persists
