### ISSUE TITLE
Reject not caught in snoowrap.updateAccessToken or credentialClientRequest

### ISSUE THREAD

**Issue by sjkelleyjr** [not-an-aardvark/snoowrap#98]
This was working for me until today when I migrated some code to another server.  Now I'm getting the following stack trace:

> Unhandled rejection RequestError: Error: Invalid protocol: null
    at new RequestError (/home/ubuntu/reemit_five34a4b/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/home/ubuntu/reemit_five34a4b/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/home/ubuntu/reemit_five34a4b/node_modules/request/request.js:123:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.self._buildRequest (/home/ubuntu/reemit_five34a4b/node_modules/request/request.js:355:39)
    at Request.init (/home/ubuntu/reemit_five34a4b/node_modules/request/request.js:533:10)
    at Request.RP$initInterceptor [as init] (/home/ubuntu/reemit_five34a4b/node_modules/request-promise/lib/rp.js:137:25)
    at new Request (/home/ubuntu/reemit_five34a4b/node_modules/request/request.js:99:8)
    at request (/home/ubuntu/reemit_five34a4b/node_modules/request/index.js:54:11)
    at snoowrap.d (/home/ubuntu/reemit_five34a4b/node_modules/request/index.js:88:14)
    at snoowrap.credentialedClientRequest (/home/ubuntu/reemit_five34a4b/node_modules/snoowrap/dist/request_handler.js:198:48)
    at snoowrap.updateAccessToken (/home/ubuntu/reemit_five34a4b/node_modules/snoowrap/dist/request_handler.js:236:17)
    at /home/ubuntu/reemit_five34a4b/node_modules/snoowrap/dist/request_handler.js:87:18
    at tryCatcher (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:454:14)
    at Promise._settlePromiseFromHandler (/home/ubuntu/reemit_five34a4b/node_modules/bluebird/js/release/promise.js:524:17)

I tried creating a new token, but that didn't help,  none of the credentials have changed throughout the migration and the old server code is working fine.

EDIT: I'm using the username and password method for authentication shown in your README, if that helps.
EDIT2: Just tried it with a refreshToken instead, same error.

**Comment by not-an-aardvark** [comment]
Could you provide an example of code that causes this issue? (You can redact the credentials if you'd like.)

**Comment by sjkelleyjr** [comment]
Of course!
`
const snoowrap = require('snoowrap');
const login = require('./USERNAME_PASS.json');
const r = new snoowrap({
        userAgent: login.reddit.userAgent,
        clientId: login.reddit.clientId,
        clientSecret: login.reddit.clientSecret,
        refreshToken:login.reddit.refresh_token
})

r.getHot().map(post => post.title).then(console.log);

exports.reddit = r;`

I just pulled down your code fresh into a new directory and tried the same code with the same credentials, and it worked fine.  I think there are some problems happening between packages with regard to dependencies.  Therefore, I think you can close this issue if you'd like
